# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273e4cfe0ee45e786783ffbf686a9b48d232a3ae8b34fde92fbb7c7306ec2e09422344e3524d770e6edfa618bf4eeac86a311e121b3882f0ee6405221a89ba13

test:
  secret_key_base: 8e3d2dd11e7b7695b6a3310e28fce5bff86d2c7b84f249302a2219a85e1930f174074e4d03a6dec0b52082ec498d70b3ed6267f798eb83d904cda725c0019859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
